apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-plex-media
spec:
  capacity:
    storage: 6000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: (IP of your NFS host)
    path: "(File path of NFS folder)"